# Generated by Django 4.2.20 on 2025-04-22 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0009_registration_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
