# Generated by Django 5.0.6 on 2025-03-11 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0014_winner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winner',
            unique_together=set(),
        ),
    ]
