# Generated by Django 4.2.20 on 2025-04-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_form_question_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='form',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='feedback.form'),
            preserve_default=False,
        ),
    ]
