# Generated by Django 5.0.6 on 2025-03-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
